version: "3"
services:
    ui:
        container_name: webapp
        build:
            context: ./client
            dockerfile: Dockerfile
        image: jun/jun:ui
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
    api:
        container_name: platform
        build:
            context: ./server
            dockerfile: Dockerfile
        image: jun/jun:api
        ports:
           - "7000:7000"
        volumes:
            - ./server:/usr/src/api
            - /usr/src/api/node_modules
    db:
        image: mongo
        ports:
           - "27017:27017"
